<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeInfo = $objectManager->create('\Hammer\WH\Settings\StoreInfo');
$adminUsername = $storeInfo->getAdminUsername();
$adminPassword = $storeInfo->getAdminPassword();
?>

<form method="post" action="" id="login-form" data-mage-init='{"form": {}, "validation": {}}' autocomplete="off">
    <fieldset class="admin__fieldset">
        <legend class="admin__legend">
            <span><?= /* @escapeNotVerified */ __('Welcome, please sign in') ?></span>
        </legend><br/>
        <input name="form_key" type="hidden" value="<?= /* @escapeNotVerified */ $block->getFormKey() ?>" />
        <div class="admin__field _required field-username">
            <label for="username" class="admin__field-label">
                <span><?= /* @escapeNotVerified */ __('Username') ?> <?= $adminUsername ? '('.$adminUsername.')' : '' ?></span>
            </label>
            <div class="admin__field-control">
                <input id="username"
                       class="admin__control-text"
                       type="text"
                       name="login[username]"
                       autofocus
                       value="<?= $adminUsername ? $adminUsername : '' ?>"
                       data-validate="{required:true}"
                       placeholder="<?= /* @escapeNotVerified */ __('user name') ?>"
                       autocomplete="off"
                />
            </div>
        </div>
        <div class="admin__field _required field-password">
            <label for="login" class="admin__field-label">
                <span><?= /* @escapeNotVerified */ __('Password') ?> <?= $adminPassword ? '('.$adminPassword.')' : '' ?></span>
            </label>
            <div class="admin__field-control">
                <input id="login"
                       class="admin__control-text"
                       type="password"
                       name="login[password]"
                       data-validate="{required:true}"
                       value="<?= $adminPassword ? $adminPassword : '' ?>"
                       placeholder="<?= /* @escapeNotVerified */ __('password') ?>"
                       autocomplete="new-password"
                />
            </div>
        </div>
        <?= $block->getChildHtml('form.additional.info') ?>
        <div class="form-actions">
            <?= $block->getChildHtml('form.buttons') ?>
        </div>
    </fieldset>
</form>
