<?php
/**
 * Show a 'View Product' link at the top of the
 * Admin > Products > Catalog > [Product] page
 *
 * @package Hammer_WH
 * @author Sebastian De Cicco <seb.decc@gmail.com>
 * @copyright 2018 Sebastian De Cicco
 * @license OSL-3.0, AFL-3.0
 */

$_product = $block->getCurrentProduct();
$_id = $_product->getId();

$_baseUrl = $block->getBaseUrl();
$_seoUrl =  $_baseUrl.$_product->getUrlKey().'.html';

$_m2BaseUrl = $_baseUrl.'catalog/product/view/id/'.$_id;
$_viewProduct = !empty($_product->getUrlKey()) ? $_seoUrl : $_m2BaseUrl;
?>
<?php if($block->getViewProduct() && $_id): ?>
    <div class="product-view-url">
        <a href="<?php echo $_viewProduct; ?>" target="_blank">View Product</a>
    </div>
<?php endif; ?>